### ISSUE TITLE
Unable to Edit itemInfo.lua

### ISSUE THREAD

**Issue by Lilori** [zackdreaver/ROenglishRE#16]
Hi,
I am wondering for this itemInfo.lua, if this .lua is fresh from it source, it will be ok.
But when i try to put custom item, there are missing lot of coma ( , ) after ( " ) in item description.

**Comment by zackdreaver** [comment]
Then you need to learn using the correct format,
and please use rathena forum for support next time if you want to add your own custom item,
I'll consider it if this official item issue.
