### ISSUE TITLE
missing some english translation for msgstringtable

### ISSUE THREAD

**Issue by hazimjauhari90** [zackdreaver/ROenglishRE#17]
tested on 2016-12-28 client..

below is the screenshot

![screen1asiaro000](https://cloud.githubusercontent.com/assets/16514357/25066856/e8daeee2-2264-11e7-9069-d22620bd67b9.jpg)
![screen1asiaro001](https://cloud.githubusercontent.com/assets/16514357/25066857/e8e20254-2264-11e7-8450-9f2f56714139.jpg)
![screen1asiaro002](https://cloud.githubusercontent.com/assets/16514357/25066854/e8d02ba6-2264-11e7-99ae-cfd81ccb02e3.jpg)
![screen1asiaro003](https://cloud.githubusercontent.com/assets/16514357/25066855/e8d8727a-2264-11e7-94fa-82509ad53c3f.jpg)

i would believe these 4 above should be displaying "Message"

![screen1asiaro004](https://cloud.githubusercontent.com/assets/16514357/25066858/e8e7c55e-2264-11e7-948c-ed66085471c5.jpg)

and this should be "More"

![screen1asiaro005](https://cloud.githubusercontent.com/assets/16514357/25066859/e8ee68be-2264-11e7-8609-56fe6f11a802.jpg)

but, for this achievement, i can't figure out the english translation.

**Comment by zackdreaver** [comment]
Have you read some comment in the forum? There are explanations about msgstringtable
https://rathena.org/board/topic/109395-2016-12-28aragexere/

**Comment by hazimjauhari90** [comment]
Yup. I do read it. This is his further note.

2. As for the read msgstringstable.txt, its possible to set your clientinfo.xml file to a langtype that will make it read the text string table. Its works with 1 (US) for sure and I think itl work with a number of others. Not bothering to test which ones tho.

I already set langtype to 1 & the client already got english translated except for those 6 above.

**Comment by zackdreaver** [comment]
It's client diff's fault, not from translated file of this project.
See, the msgstringtable parsed correctly but not the TranslateClient.qs from NEMO patch.

**Comment by hazimjauhari90** [comment]
u mean these korean text above not from msgstringtable.txt but instead it is from TranslateClient.qs from Nemo Patch?

but I doubt there will be update from owner.
Well.. i have that feeling too.. because of this, i think most of the server owner will got stuck up to 2015 client only.. it will be useless to implement more newer client but got some fault in diff the client...

anyway, i think this topic can be close already.. sorry for borrowing ur time to have a look on not the incorrect reported isssue here.. xD

**Comment by zackdreaver** [comment]
It's okay. Closing this now.

**Comment by hazimjauhari90** [comment]
i know this is not the appropriate place to address issue, but at the original repo i cannot report the issue.

could u please check the 2014-10-22bRagexe client.. i think u uploaded the already patched client with nemo.. below is the screenshot.. i put a try to diff with nemo.. got few errors.. at first i didn't realize the client already patched with nemo until i see its name, 2014-10-22bRagexe_patched.exe

![2014-10-22bragexe](https://cloud.githubusercontent.com/assets/16514357/25072684/2bc61db4-2308-11e7-89b6-a45e3183d193.png)
