### ISSUE TITLE
missing summoner expanded skills in skill tree window

### ISSUE THREAD

**Issue by hazimjauhari90** [zackdreaver/ROenglishRE#18]
based on this PR & update branch on rathena repo

https://github.com/rathena/rathena/pull/1965
https://github.com/rathena/rathena/tree/update/summoner_expanded

those following are the missing for summoner expanded skills in skill tree window
skill ID 5044 SU_SOULATTACK##
skill ID 5045 SU_POWEROFFLOCK## - 
skill ID 5046 SU_SVG_SPIRIT## - 
skill ID 5047 SU_HISS## - 
skill ID 5048 SU_NYANGGRASS## - 
skill ID 5049 SU_GROOMING## -
skill ID 5050 SU_PURRING##
skill ID 5051 SU_SHRIMPARTY## - 
skill ID 5052 SU_SPIRITOFLIFE##
skill ID 5053 SU_MEOWMEOW## - 
skill ID 5054 SU_SPIRITOFLAND## - 
skill ID 5055 SU_CHATTERING## -
skill ID 5056 SU_SPIRITOFSEA##

**Comment by zackdreaver** [comment]
I have added translated of those skills long before rA starting those skills
data\luafiles514\lua files\skillinfoz\RebellionRE

**Comment by hazimjauhari90** [comment]
I have a look on them just now.. by replacing those lua files inside the skillinfoz folder did the trick. They work like a champ.. once again, i'm sorry for creating false alarm on u.

Anyway, is there any medium i could contact u.? There is something i would like to hand over to u. I guess it will be part of ur RO stuff related collection & i did sent u a PM on rA forum..

**Comment by zackdreaver** [comment]
If it related to project I created,
you're welcome to open an issue or Pull Ruquest, and we can dicuss everything related to topic.

Other than that, i can't provide any help regarding service or anything related to it.

Closing this now.
