### ISSUE TITLE
Item #6457

### ISSUE THREAD

**Issue by nanakiwurtz** [zackdreaver/ROenglishRE#2]
On current iteminfo.lua (in this repo), item 6457 is Safe to 10 Certificate
But on http://ro.gnjoy.com/guide/runemidgarts/itemview.asp?itemSeq=7&ID=6457 is +5 ticket for Armor
Google Translate:
> 5 armor smelting guaranteed rights
Armor 5 images smelting guaranteed rights
It can through the Frontera smelting researchers also strengthen the smelting of armor to step 5. Limited -1 times -
Weight: 0

**Comment by zackdreaver** [comment]
Thanks
Ok I'll look into it,

fyi, mostly all items are came from iRO's desc, so it's need many fixes...and a long way to go before it's truly follow kRO's.
