### ISSUE TITLE
ItemInfo.lua

### ISSUE THREAD

**Issue by mazvi** [zackdreaver/ROenglishRE#21]
Zack tolong cek pada item nomor 13081

disana masih berbahasa korea, dikarang saja daripada begitu.

oiya untuk editor teks pakai apa ya? saya pakai notepad++ selalu bahasanya jadi UTF dikembalikan ke ANSI hasilnya berbeda tidak seperti notepad biasa bisa ASCII

kamu editor teks lua pakai apa?

makasih zack

**Comment by zackdreaver** [comment]
I don't have much time to update iteminfo anymore, my focus right to add support to latest client.
Default setting of NPP should be good enough to edit iteminfo, please use ra forum instead if you need support that isn't related to this project.
