### ISSUE TITLE
pcJobbl2 instead of pcJobTbl

### ISSUE THREAD

**Issue by vBrenth** [zackdreaver/ROenglishRE#23]
https://github.com/zackdreaver/ROenglishRE/blob/8f3fa3cc7d307bf7e708ad88e60032b744db61eb/data/luafiles514/lua%20files/admin/pcjobnamegender.lub#L69

Not sure if its a bug or not.

**Comment by zackdreaver** [comment]
That came by default from kRO's data grf, I'm not going to change it unless I or someone whose know better about this tell it's wrong.
