### ISSUE TITLE
Format fix, don't know how to pull request XP.

### ISSUE THREAD

**Issue by vBrenth** [zackdreaver/ROenglishRE#24]
https://github.com/zackdreaver/ROenglishRE/blob/8f3fa3cc7d307bf7e708ad88e60032b744db61eb/data/luafiles514/lua%20files/signboardlist.lub#L6

Formatting?
https://pastebin.com/XB6zxhwa

**Comment by zackdreaver** [comment]
That is github's auto detection encoding fault, there will be now problem if your github client, such tortoise git, use ascii as default encoding.
