### ISSUE TITLE
missing some english translation of msgstringtable.txt for 2017-08-01aRagexeRE & newer clients

### ISSUE THREAD

**Issue by Mikegyver** [zackdreaver/ROenglishRE#26]
tested on 2017-08-01aRagexeRE client..

below are the screenshots

![screen000](https://user-images.githubusercontent.com/16514357/30249258-3b9f67aa-966b-11e7-93c4-4dd0d3bcb16d.jpg)

![screen001](https://user-images.githubusercontent.com/16514357/30249257-3b932ff8-966b-11e7-95cc-6c20e936f140.jpg)

**Comment by zackdreaver** [comment]
I don't have this client, unless you can extract the msgstringtable for me

**Comment by dekspyware** [comment]
" tested on 2018-08-01aRagexeRE client.. ? "
lol you are from future ?

**Comment by NandoPrates** [comment]
@zackdreaver data compatible with which hexed?

**Comment by Asheraf** [comment]
@zackdreaver here is RAW msgstringtable from 2017-11-08bRagexeRE.
https://1drv.ms/t/s!AkBvy4BwwKPCmipcU_-_PbQVG093
