### ISSUE TITLE
itemID: 20515 - Position

### ISSUE THREAD

**Issue by admkakaroto** [zackdreaver/ROenglishRE#29]
I have a problem and at the same time a doubt about this item, it uses hateffect to be displayed in the character, however after updating with the files here of the repository the item appears in the incorrect position in the character, I tried to correct the position but it does not work, he is not below the character.

Does this have any connection to the client version? Use 2017-05-31.

IMG: https://i.imgur.com/cka7bTY.png

**Comment by zackdreaver** [comment]
What's your client date?

I guess it need november client, as older client don't support isRenderBeforeCharacter

jRO preview:
https://ragnarokonline.gungho.jp/news/information/kue8e6000002yk15-img/a1509415600748.gif

**Comment by zackdreaver** [comment]
Can you give me a replay file (rrf) of you wearing this costume?

**Comment by admkakaroto** [comment]
Here:

[itemreplay.zip](https://github.com/zackdreaver/ROenglishRE/files/1524116/itemreplay.zip)

**Comment by zackdreaver** [comment]
I've tested it, its indeed need november client or newer,
but still, there is no transparency effect, I guess kRO client doesn't support this garment.

and btw, this issue has nothing to do with translation, so I will close this.
