### ISSUE TITLE
resource errors from Hell Fly (Mob-ID#1872)

### ISSUE THREAD

**Issue by im-mi** [zackdreaver/ROenglishRE#33]
**Client version:** 2015-11-04a (fully updated as of 2018-01-07)
**ROenglishRE version:** 631eb6f4fb114c6dbef3c9468ea28eb93a54f07a

I'm getting the following resource errors whenever a Mob-ID#1872 ("Hell Fly") appears:
> Spr :: Cannot find File : sprite\????\hell_fly.spr
Cannot find File : sprite\????\hell_fly.act

I also managed to fix it myself by changing its sprite from HELL_FLY to HUNTER_FLY. However, I'm not sure if that's the correct solution.

The following line was changed:
https://github.com/zackdreaver/ROenglishRE/blob/631eb6f4fb114c6dbef3c9468ea28eb93a54f07a/data/luafiles514/lua%20files/datainfo/jobname.lub#L1363

**Comment by Daegaladh** [comment]
hell_fly.spr and .act can be found in jRO's data.grf

**Comment by im-mi** [comment]
Strange... my data.grf doesn't contain hell_fly.spr/.act. Maybe that's because my data.grf is from kRO instead of jRO like your hell_fly files. Regardless, since it works fine without ROenglishRE installed, kRO must be using a different sprite, right?

I also think adding the files you provided to data.grf manually would work, but I haven't been able to test it since I haven't had any luck with grf editors (adding files seems to cause other resource errors (I suspect due to weirdness involving ASCII encoding + hangul characters)).

**Comment by Daegaladh** [comment]
No, kRO doesn't have those files because they use HUNTER_FLY in their jobname.lub.
But they still use HELL_FLY for other mob (unused) tho:
`[jobtbl.JT_HELL_FLY] = "HELL_FLY",`

**Comment by im-mi** [comment]
> No, kRO doesn't have those files because they use HUNTER_FLY in **their jobname.lub**.

Huh? Does that mean there's an alternate jobname.lub for kRO? I only see two files named jobname.lub in the repository, and both use HELL_FLY. Or maybe I'm misunderstanding ROenglishRE as being primarily intended for kRO.

**Comment by Daegaladh** [comment]
I don't know why @zackdreaver used HELL_FLY instead of HUNTER_FLY, but in kRO's data.grf the jobname.lub file says
`[jobtbl.JT_BEELZEBUB_FLY] = "HUNTER_FLY",`

**Comment by im-mi** [comment]
Ah, then I'll just keep it as HUNTER_FLY on my end for kRO compatibility. Thanks for the confirmation.

So maybe kRO compatibility isn't the priority in this case. Or, if it is, it could be a small oversight. I'll keep this issue open for now, at least until it can be confirmed that it's intentional.
