### ISSUE TITLE
System/Iteminfo.lua

### ISSUE THREAD

**Issue by TheDerpySupport** [zackdreaver/ROenglishRE#34]
When trying to add new lines such as a custom item you are met with a series of bad lines such as 	`"'n?U?y???,` (taken from line 133985) and will not allow you to log into the game.

**Comment by zackdreaver** [comment]
there is itemInfo.zip, use that one

**Comment by TheDerpySupport** [comment]
Still seems to throw the errors when I try to add anything new 
![image](https://user-images.githubusercontent.com/21302014/35175426-3f520a4e-fd39-11e7-8505-4a26683da376.png)

**Comment by TheDerpySupport** [comment]
I was trying to help someone add a new custom and any time I put 
```
	[32100] = {
		unidentifiedDisplayName = "Wings",
		unidentifiedResourceName = "Arctic",
		unidentifiedDescriptionName = { "Unknown Item, can be identified by using a ^6666CCMagnifier^000000." },
		identifiedDisplayName = "Arctic Wings",
		identifiedResourceName = "Arctic",
		identifiedDescriptionName = { "[Custom item]", },
		slotCount = 0,
		ClassNum = 1704
	},
``` into the iteminfo.lua it gives me the above error messages

**Comment by zackdreaver** [comment]
What's your text editor?
might be encoding issue when saving the file,
try to turn off auto detect encoding, if there any.
It's best to automatically set it to ascii.

**Comment by TheDerpySupport** [comment]
I use Notepad++

**Comment by zackdreaver** [comment]
yes, set it to ascii first then open the vanilla one then check line 133985
are there any ??? characters

**Comment by TheDerpySupport** [comment]
Yeah after correcting the encoder to ANSI i was able to properly view the files; Thanks for putting up with this lol First time i've ever had this happen when modifying files
