### ISSUE TITLE
Unicode message on Wrong Password

### ISSUE THREAD

**Issue by TheDerpySupport** [zackdreaver/ROenglishRE#35]
http://puu.sh/zfsrs/8396a0c52f.png

I tried scouring all of the msgstringinfo files, system, etc but I couldnt find where this is.
2017-06-14b Client

**Comment by Daegaladh** [comment]
That's hardcoded in the exe. You need to hex that message.

**Comment by TheDerpySupport** [comment]
Well that sucks... I'll have to remember this down the road so I can find someone who can do that for me lol
