### ISSUE TITLE
suport for new clients

### ISSUE THREAD

**Issue by hederod** [zackdreaver/ROenglishRE#36]
to run with new clients
needs some changes
i noticed on 2017-11-01bRagexeRE was it has 8th argument on itemInfo.lua
the costume line (true or false)
I tested on an iteminfo with just one item
but the change has to be done on all items
Do you know any easy way to do it?
intends to work with new clients ?

[607] = {
		unidentifiedDisplayName = "Yggdrasil Berry",
		unidentifiedResourceName = "이그드라실열매",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Yggdrasil Berry",
		identifiedResourceName = "이그드라실열매",
		identifiedDescriptionName = {
			"Fruit from the Yggdrasil tree which brings life to our world. Its fantastic taste is full of life.",
			"^FFFFFF_^000000",
			"Class:^0000FF Restorative item^000000",
			"Heal:^006600 100%^000000 HP, ^006600100%^000000 SP",
			"Weight:^006600 30^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},

and smal change on function

main = function()
	for ItemID, DESC in pairs(tbl) do
		result, msg = AddItem(ItemID, DESC.unidentifiedDisplayName, DESC.unidentifiedResourceName, DESC.identifiedDisplayName, DESC.identifiedResourceName, DESC.slotCount, DESC.ClassNum, DESC.costume)
		if not result == true then
			return false, msg
		end
		for k, v in pairs(DESC.unidentifiedDescriptionName) do
			result, msg = AddItemUnidentifiedDesc(ItemID, v)
			if not result == true then
				return false, msg
			end
		end
		for k, v in pairs(DESC.identifiedDescriptionName) do
			result, msg = AddItemIdentifiedDesc(ItemID, v)
			if not result == true then
				return false, msg
			end
		end
		k = DESC.costume
		k = DESC.unidentifiedResourceName
		v = DESC.identifiedDisplayName
	end
	return true, "good"
end

I tested on an iteminfo with just one item

**Comment by lelouch22** [comment]
The newer clients reads itemInfo_true.lub rather the itemInfo.lub

**Comment by hederod** [comment]
i think just need change function add new line and rename file

**Comment by zackdreaver** [comment]
Read project description, thanks.
