### ISSUE TITLE
Korean languange when using storage at 2018 Client

### ISSUE THREAD

**Issue by hendra814** [zackdreaver/ROenglishRE#41]
Hi Zack, i'm want help you for 2018 client for storage client problem
here the files to fix korean languange
[storage2018.zip](https://github.com/zackdreaver/ROenglishRE/files/1888230/storage2018.zip)

**Comment by zackdreaver** [comment]
Is this yours or someone else's textures?

**Comment by hendra814** [comment]
no, that files from my discord friend.

**Comment by zackdreaver** [comment]
Have you got his permission to share this files?

**Comment by hendra814** [comment]
Yup, i'm already ask him

**Comment by M45T3Ryu** [comment]
kRO used these textures before they are official

**Comment by M45T3Ryu** [comment]
for 2010 clients i think

**Comment by zackdreaver** [comment]
Then we should credit him, what is his name?

**Comment by hendra814** [comment]
On Discord his name is JunhoYoon
