### ISSUE TITLE
Missing renewal party icon for new job Star Emperror and Soul Reaper

### ISSUE THREAD

**Issue by hendra814** [zackdreaver/ROenglishRE#44]
Rathena already enable this new job, when try create party got crash for icon job

here my ss
![image png 754a632a05b80ccfa826b20c5b39caa0](https://user-images.githubusercontent.com/9587609/41634245-073a193e-746d-11e8-9a2d-d12034cc68bb.png)

**Comment by hendra814** [comment]
@zackdreaver 
are you already retired ?
not have any update for a few months

**Comment by zackdreaver** [comment]
I'll wait a new stable unpacked ragexe client released by rA,
until then I'm not gonna touch those new classess.
