### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Miraakol** [zackdreaver/ROenglishRE#48]
sir @zackdreaver just wanted to ask is this compatible with newer 2018 ragexe client?

**Comment by zackdreaver** [comment]
nope

**Comment by Miraakol** [comment]
thanks sir @zackdreaver what client are compatible with your client translation?

**Comment by Miraakol** [comment]
and also what's the use of dev folder?

**Comment by zackdreaver** [comment]
up to 2017-05-17bRagexeR
DEV= developer

**Comment by Miraakol** [comment]
many thanks! @zackdreaver
