### ISSUE TITLE
skill tree tab unaligned

### ISSUE THREAD

**Issue by Miraakol** [zackdreaver/ROenglishRE#49]
![image](https://user-images.githubusercontent.com/4651777/46345742-4624eb80-c678-11e8-9e06-30aeb9976db3.png)

how to fix this? im using 20151104ragexe and your translation data.

**Comment by Miraakol** [comment]
actually im using different emulator. the one i use still doesnt support this kind of skills.

**Comment by zackdreaver** [comment]
Here use this, if you don't know how to get the old version.
[skillinfoz.zip](https://github.com/zackdreaver/ROenglishRE/files/2437682/skillinfoz.zip)

**Comment by Miraakol** [comment]
is this from your data folder @zackdreaver ? the one you provided?

**Comment by zackdreaver** [comment]
yes

**Comment by Miraakol** [comment]
thanks! @zackdreaver

**Comment by Miraakol** [comment]
question, is this based to latest update w/o the new skills implemented?

**Comment by Miraakol** [comment]
no, im using exneval's idathena.

**Comment by Miraakol** [comment]
idathena's core is rathena

**Comment by zackdreaver** [comment]
then you can use the files I gave you just fine, though when the skills are updated
and you still want to use 20151104, you need to hack its skillid so they appear in 3rd tab skills.
