### ISSUE TITLE
open windows skill, client crash using 2018-06-21

### ISSUE THREAD

**Issue by hendra814** [zackdreaver/ROenglishRE#53]
using client 20180621 client always got crash when open windows skill.

**Comment by zackdreaver** [comment]
As I said in another issue page, I'll only give support for 2018 client when rA developer
provide the clients, not from another emulator site or some random user that release it.
https://rathena.org/board/topic/86650-officially-supported-client-versions/

until then, please enjoy the current stable client that this project supported.
