### ISSUE TITLE
Missing ^000000

### ISSUE THREAD

**Issue by Everade** [zackdreaver/ROenglishRE#57]
You didn't include all fixes from my last report.

Following skills miss a **^000000** at the end of their description which renders all following colors wrong:
```
SKID.LG_PINPOINTATTACK
SKID.LG_OVERBRAND
SKID.LG_MOONSLASHER
```

**Example:**
![image](https://user-images.githubusercontent.com/12261601/50426315-207c3c80-088b-11e9-873c-81cbc502d7db.png)

Affected files:
**Skill Description Lua**

**Comment by zackdreaver** [comment]
That's intended.
"requires" (and "consumes") is part of "Description", therefore the color should like the rest item under description.

Coloring item, skill and equipment under description is special case, in which this project aim to bring RO on a par with other modern mmorpg.

**Comment by Everade** [comment]
Hmm... ok
Maybe i've overseen something.

I've *fixed* this years ago. Back then, the coloring was entirely messed up because of that.
So i'm 100% sure it was wrong back then.
