### ISSUE TITLE
Quest Windows Client Crash

### ISSUE THREAD

**Issue by alxalmora** [zackdreaver/ROenglishRE#6]
Hi, well everything works fine but, in Quest Window (Alt + U) special in mora Daily Hunting Quest when select your quest Client Crash. Using 2015-11-04aRagexe in rAthena.

**Comment by alxalmora** [comment]
Close, already solved. Replacing some things.

**Comment by zackdreaver** [comment]
SO,
Are you solving this with the files this project have, or with your own file?

**Comment by alxalmora** [comment]
Yes, Replace both /lua files and /luafiles from grf and /System folder
