### ISSUE TITLE
Error using client 2018-06-21a

### ISSUE THREAD

**Issue by AzarthMZintos** [zackdreaver/ROenglishRE#68]
I got this error using this transalation if a block it using data.ini the client load normaly:

![error](https://user-images.githubusercontent.com/35034692/56996362-9fa3b900-6b7a-11e9-9965-c18e2ea3f507.png)

this happen after execute the client so no other window besides the error

**Comment by zackdreaver** [comment]
No idea, but i'm sure its not related with the translation, rA forum is your best bet to solve this.
