### ISSUE TITLE
iteminfo.lub problem

### ISSUE THREAD

**Issue by mrlongshen** [zackdreaver/ROenglishRE#7]
Hi zack, can you check this ? 
http://prntscr.com/ckxxc6

**Comment by zackdreaver** [comment]
Is this an error you got from using itemInfo from this project or your own custom work? This project doesn't have any files with iteminfo.lub name extension.
If this your own custom work, then sorry to dissapoint you, I'm not providing such help in issue page, please use rA forum instead.

**Comment by mrlongshen** [comment]
Hi zack, I'm using this project iteminfo.lua. I rename it using notepad ++ from iteminfo.lua to iteminfo.lub
So my method is wrong or ? Any suggestion.. ?

**Comment by zackdreaver** [comment]
Suggestion? 
don't follow a guide that told you to change file extension or even decompile/compile it.
the lua extension is already good, it's won't be replaced when you update kRO client.
